### ISSUE TITLE
求发新版呀

### ISSUE THREAD

**Issue by fantix** [jpush/jpush-api-python-client#18]
都快一年没发 PyPI 新版了，支持 Python 3 的 PR merge 了也半年了，广大 Python 3 用户求 pip 安装呀。

**Comment by 0bit** [comment]
PyPI更新一下吧！

**Comment by hupantingxue** [comment]
ok

**Comment by hupantingxue** [comment]
The latest version has uploaded!
https://pypi.python.org/pypi/jpush/3.1.0

**Comment by fantix** [comment]
:+1:
