### ISSUE TITLE
ios无法收到推送的消息

### ISSUE THREAD

**Issue by Jimmy-Xu** [jpush/jpush-api-python-client#22]
使用python调用jpush分别发送消息给android和ios，代码如下：

	[root@aps push]# cat example_platformmsg.py
	import jpush as jpush
	from conf import app_key, master_secret
	_jpush = jpush.JPush(app_key, master_secret)

	push = _jpush.create_push()
	push.audience = {'registration_id': ["030fdxxxx8a","071b8xxxx15"]}
	push.notification = jpush.notification(alert="Hello, JPush!(send by python)")
	push.platform = jpush.all_
	push.send()

	[root@aps push]# python example_platformmsg.py
	{"sendno":"0","msg_id":"363809640"}

android能收到，但是ios无法收到!

而使用jpush web测试推送，android和ios都可以收到消息。

**Comment by hupantingxue** [comment]
您好，您发送的registration id只有 "audience": {"registration_id": ["030xxxa88a"]} 这个

**Comment by shi1991** [comment]
ios推送分为开发环境和发布环境两个环境。通过设置 options 中的 "apns_production":False 表示开发环境，默认不填为发布环境
如果还无法推送，通过极光推送的web平台手动推送，查找是否原因，还有一种可能就是证书配置失败。
