### ISSUE TITLE
Python SDK 如何控制IOS平台为开发环境还是生产环境

### ISSUE THREAD

**Issue by shi1991** [jpush/jpush-api-python-client#29]
Python SDK 如何控制IOS平台为开发环境还是生产环境

**Comment by fendouai** [comment]
如果目标平台为 iOS 平台 需要在 options 中通过 apns_production 字段来制定推送环境。True 表示推送生产环境，False 表示要推送开发环境； 如果不指定则为推送生产环境。
http://docs.jpush.io/server/rest_api_v3_push/#platform

True 表示推送生产环境，False 表示要推送开发环境；如果不指定则为推送生产环境。JPush 官方 API LIbrary (SDK) 默认设置为推送 “开发环境”。

http://docs.jpush.io/server/rest_api_v3_push/#options
