### ISSUE TITLE
jpush/push/payload.py 中def android的参数alert没有默认值None

### ISSUE THREAD

**Issue by HunDunDM** [jpush/jpush-api-python-client#34]
jpush/push/payload.py
78行
def android(alert, title=None, builder_id=None, extras=None):
应为
def android(alert=None, title=None, builder_id=None, extras=None):

注释中说明了All keyword arguments are optional.

**Comment by fendouai** [comment]
感谢反馈，注释中的说明不够清楚，以 REST 文档的为准：“ alert：这里指定了，则会覆盖上级统一指定的 alert 信息；内容可以为空字符串，则表示不展示到通知栏。”
REST 文档地址：https://docs.jiguang.cn/jpush/server/push/rest_api_v3_push/#notification
稍后更新一下注释，alert 可以为空字符串。
