### ISSUE TITLE
 No connection adapters were found for ' https://api.jpush.cn/v3/push'

### ISSUE THREAD

**Issue by variantf** [jpush/jpush-api-python-client#38]
I think there's an extra space on BASE_URL in common.py

**Comment by variantf** [comment]
BASE_URL = " https://api.jpush.cn/"
_______________^____

**Comment by fendouai** [comment]
Thank you,the issue is fixed.

**Comment by TvnyI** [comment]
a

**Comment by TvnyI** [comment]
why'd you close it
could you tell me how you fixed it?

**Comment by MarkPuchalaII** [comment]
I mean.. did they not simply remove the space before the https?
