### ISSUE TITLE
是否不支持title,body的ios推送？

### ISSUE THREAD

**Issue by eyvallah** [jpush/jpush-api-python-client#39]
直接用apns的推送里title是粗体显示，python的api里面好像不支持？

**Comment by helperhaps** [comment]
https://github.com/jpush/jpush-api-python-client/blob/master/examples/push_examples/example_notification.py#L12

将 alert 的值换成一个相应的 dict 就行了，我记得没错的话，键应该是 title, subtitle 和 body 吧

**Comment by eyvallah** [comment]
的确是这样，本来看文档里面说alert里面要求是String，还以为不能传字典
