### ISSUE TITLE
超时的时候无法确认是否 极光有处理

### ISSUE THREAD

**Issue by watermelo** [jpush/jpush-api-python-client#48]
![image](https://user-images.githubusercontent.com/14182114/53862698-1f058800-4023-11e9-825a-b25bfb857560.png)
如果是ConnectTimeout 客户端可以重试，如果是ReadTimeout 客户端直接可以丢弃。现在所有的超时异常返回的都是APIConnectionException， 没法判断是否需要重发。

**Comment by helperhaps** [comment]
是的，是这边代码写的不对马上会发个版本修复
